options:
  port:
    type: int
    default: 8888
    description: "The port to run OpsCenter on"
  interface:
    type: string
    default: None
    description: ""
  int-option:
    type: int
    default: 9001
    description: "A short description of the configuration option"

