#!/bin/bash

set -eux

apt-get update

apt-get install curl -y

#Add the datastax repository
if ! [ -f "/etc/apt/sources.list.d/datastax.community.list" ]; then
    echo "deb http://debian.datastax.com/community stable main" | \
    tee -a /etc/apt/sources.list.d/datastax.community.list

    curl -L http://debian.datastax.com/debian/repo_key | apt-key add -
    apt-get update
fi

